apiVersion: v1
kind: Secret
metadata:
  name: example-provider-secret
type: Opaque
data:
  BaseUrl: aHR0cHM6Ly9hcGkubWdtdC5jbG91ZC52bXdhcmUuY29t
  credentials: NHI0OER3bW8tUGVlZDJvSXBrOC1BRXhaaXFrTGpiRUllUjlkNHhHcTNNa2VYNzAwQzRQdkZ2c054dW5NLTdMRA==
---
apiVersion: ankatest.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
